version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - frontend-dependencies-{{ checksum "~/project/frontend/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - frontend-dependencies-

      - run:
          name: "Install"
          command: yarn install
          working_directory: ~/project/frontend
      - save_cache:
          paths:
            - node_modules
          key: frontend-dependencies-{{ checksum "~/project/frontend/package.json" }}

      - run:
          name: "Build"
          command: "yarn build"
          working_directory: ~/project/frontend
      - run:
          name: "Deploy to Firebase"
          command: "./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN"
          working_directory: ~/project/frontend
