version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run: ls
      - checkout
      - run: pwd
      - run: ls
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install"
          command: yarn install
          working_directory: ~/project/frontend
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      #- run: yarn test
      - run:
          name: "Build"
          command: "yarn build"
          working_directory: ~/project/frontend
      - run:
          name: "Deploy to Firebase"
          command: "./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN"
          working_directory: ~/project/frontend
