[package]
name = "absorbtv-db_updater"
version = "0.1.0"
authors = ["Roger Andersen <hexjelly@hexjelly.com>"]
edition = "2018"

[dependencies]
serde = "1.0.85"
serde_json = "1.0.37"
mockito = "0.15.0"
